#!/usr/bin/env python3
"""Download targeted NOD-EEG (ds005811) files from OpenNeuro.

Default behavior downloads the lightweight development subset for one subject:
raw continuous FIF run(s), the subject epoch FIF, detailed events CSV, stimulus
metadata, and dataset metadata.

For CLIP embedding prep, pass an include-list generated by
`scripts/generate_clip_embeddings.py --write-openneuro-include-list` to download
only the referenced ImageNet stimulus images.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable


DATASET_ID = "ds005811"
DEFAULT_SUBJECT = "sub-01"
DEFAULT_OUTPUT_DIR = "data/raw/nod"


def parse_runs(value: str) -> list[int]:
    """Parse comma/range run specs like `1,2,5` or `1-5`."""
    runs: set[int] = set()
    for part in value.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            start_s, end_s = part.split("-", 1)
            start, end = int(start_s), int(end_s)
            if start > end:
                raise argparse.ArgumentTypeError(f"Invalid run range: {part}")
            runs.update(range(start, end + 1))
        else:
            runs.add(int(part))
    if not runs:
        raise argparse.ArgumentTypeError("At least one run is required")
    return sorted(runs)


def default_include_patterns(
    *,
    subject: str = DEFAULT_SUBJECT,
    session: str = "ImageNet01",
    runs: Iterable[int] = (1,),
    include_epochs: bool = True,
    include_metadata: bool = True,
) -> list[str]:
    """Build targeted OpenNeuro include paths for NOD development work."""
    patterns = [
        f"derivatives/preprocessed/raw/{subject}_ses-{session}_task-ImageNet_run-{run:02d}_eeg_clean.fif"
        for run in runs
    ]
    if include_epochs:
        patterns.append(f"derivatives/preprocessed/epochs/{subject}_eeg_epo.fif")
    patterns.append(f"derivatives/detailed_events/{subject}_events.csv")
    if include_metadata:
        patterns.extend([
            "stimuli/metadata/*",
            "dataset_description.json",
            "participants.tsv",
            "participants.json",
        ])
    return patterns


def read_include_list(path: str | Path) -> list[str]:
    """Read newline-delimited OpenNeuro include paths, ignoring blanks/comments."""
    includes: list[str] = []
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            includes.append(line)
    return includes


def download_patterns(dataset: str, target_dir: str | Path, patterns: Iterable[str], *, dry_run: bool = False) -> None:
    """Download each include path separately so partial failures are visible."""
    patterns = list(patterns)
    if not patterns:
        raise ValueError("No OpenNeuro include patterns were provided")

    target = Path(target_dir)
    target.mkdir(parents=True, exist_ok=True)

    if dry_run:
        print(f"Dataset: {dataset}")
        print(f"Target:  {target}")
        for pattern in patterns:
            print(pattern)
        return

    import openneuro  # Imported lazily so --dry-run works without project deps installed.

    for pattern in patterns:
        print(f"\n=== Downloading: {pattern} ===")
        try:
            openneuro.download(
                dataset=dataset,
                target_dir=str(target),
                include=[pattern],
            )
        except Exception as exc:  # OpenNeuro partial availability can vary; keep going.
            print(f"  Warning: {exc}")
            print("  Continuing with next pattern...")

    print(f"\nDone! NOD-EEG files downloaded to {target}/")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dataset", default=DATASET_ID)
    p.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR)
    p.add_argument("--subject", default=DEFAULT_SUBJECT)
    p.add_argument("--session", default="ImageNet01")
    p.add_argument("--runs", type=parse_runs, default=parse_runs("1"), help="Run list/range, e.g. `1` or `1-5`")
    p.add_argument("--no-epochs", action="store_true", help="Skip the concatenated subject epochs FIF")
    p.add_argument("--no-metadata", action="store_true", help="Skip stimulus/dataset metadata side files")
    p.add_argument(
        "--include-list",
        help="Newline-delimited OpenNeuro include paths, e.g. targeted ImageNet stimuli from generate_clip_embeddings.py",
    )
    p.add_argument("--dry-run", action="store_true", help="Print include paths without downloading")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    patterns = default_include_patterns(
        subject=args.subject,
        session=args.session,
        runs=args.runs,
        include_epochs=not args.no_epochs,
        include_metadata=not args.no_metadata,
    )
    if args.include_list:
        patterns.extend(read_include_list(args.include_list))

    # Preserve order while removing duplicates.
    patterns = list(dict.fromkeys(patterns))
    download_patterns(args.dataset, args.output_dir, patterns, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
